all:
  children:
    renaissance:
      hosts:
        adunda:
          ansible_host: 192.168.77.150
          ansible_user: adunda
          ansible_ssh_private_key_file: /Users/nikita/ansible/ssh/adunda
        diamond:
          ansible_host: 192.168.77.151
          ansible_user: diamond
          ansible_ssh_private_key_file: /Users/nikita/ansible/ssh/diamond
        alice:
          ansible_host: 192.168.77.152
          ansible_user: alice
          ansible_ssh_private_key_file: /Users/nikita/ansible/ssh/alice
        pantera:
          ansible_host: 192.168.77.153
          ansible_user: pantera
          ansible_ssh_private_key_file: /Users/nikita/ansible/ssh/pantera
