---
- name: Update-packages
  hosts: renaissance
  become: yes

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
      become: yes
