---
- name: cron-autossh-install
  hosts: renaissance # master
  become: yes

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: install cron
      apt:
        name: cron
        state: latest

    - name: install autossh
      apt:
        name: autossh
        state: latest

    - name: install fzf
      apt:
        name: fzf
        state: latest

    - name: install nfs-common
      apt:
        name: nfs-common
        state: latest

    # sudo systemctl restart kubelet
    # - name: NFS restart kubelet
    #   become: yes
    #   ansible.builtin.shell: >
    #     sudo systemctl restart kubelet

    - name: install silversearcher-ag
      apt:
        name: silversearcher-ag
        state: latest

    - name: install ripgrep
      apt:
        name: ripgrep
        state: latest

    - name: clone kubectx
      become: yes
      ansible.builtin.git:
        repo: https://github.com/ahmetb/kubectx
        dest: /opt/kubectx
        version: master

    # Analogs for these commands:
    #ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx;
    #ln -s /opt/kubectx/kubens /usr/local/bin/kubens
    - name: Ensure kubectx is symlinked
      become: yes
      ansible.builtin.file:
        src: /opt/kubectx/kubectx
        dest: /usr/local/bin/kubectx
        state: link
        force: yes

    - name: Ensure kubens is symlinked
      become: yes
      ansible.builtin.file:
        src: /opt/kubectx/kubens
        dest: /usr/local/bin/kubens
        state: link
        force: yes
