---
- name: htop-vim-install
  hosts: renaissance
  become: yes

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: install git
      apt:
        name: git
        state: latest

    - name: install htop
      apt:
        name: htop
        state: latest

    - name: install curl
      apt:
        name: curl
        state: latest

    - name: install vim
      apt:
        name: vim
        state: latest

    - name: install rsync
      apt:
        name: rsync
        state: latest

    - name: Ensure apt-utils is installed
      ansible.builtin.apt:
        name: apt-utils
        state: present

    - name: install python3
      apt:
        name: python3
        state: latest

    - name: install unzip 
      apt:
        name: unzip 
        state: latest

    - name: Install python3-venv
      apt:
        name: python3-venv
        state: latest
      become: yes

    - name: install python3-virtualenv
      apt:
        name: python3-virtualenv
        state: latest

    - name: install python3-pip
      apt:
        name: python3-pip
        state: latest

    - name: Install pynvim within the virtual environment using Ansible pip module
      become: yes
      ansible.builtin.pip:
        name: pynvim
        virtualenv: /opt/neovim_venv
        virtualenv_command: /usr/bin/python3 -m venv

    - name: pip with python 3.12 fix
      ansible.builtin.shell: |
        python3 -m pip config set global.break-system-packages true
        python3 -m pip install --user --upgrade pynvim

    - name: Install yapf globally
      become: yes
      ansible.builtin.pip:
        name: yapf
        state: latest

    - name: install golang-go
      apt:
        name: golang-go
        state: latest

    - name: install thefuck
      become: yes
      ansible.builtin.pip:
        name: thefuck
        extra_args: --user
