---
- name: cron-autossh-install
  hosts: renaissance # master
  become: yes

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: install cron
      apt:
        name: cron
        state: latest

    - name: install autossh
      apt:
        name: autossh
        state: latest

    - name: install fzf
      apt:
        name: fzf
        state: latest

    - name: install silversearcher-ag
      apt:
        name: silversearcher-ag
        state: latest

    - name: install ripgrep
      apt:
        name: ripgrep
        state: latest
