# ansible-playbook playbook.yml --extra-vars "env=prod"

---
- name: htop-vim-install
  hosts: renaissance # nodes
  become: yes

  vars_files:
    - secret_vars_common.yml
    - "secret_vars_k3s_nodes_{{ env }}"
    #- secret_vars_k3s_nodes.yml

  tasks:
    - name: Install k3s on nodes
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ server }}:6443 K3S_TOKEN={{ token }} sh -
