all:
  children:
    renaissance:
      hosts:
        latte:
          ansible_host: 192.168.77.170
          ansible_user: latte
          ansible_ssh_private_key_file: /Users/nikita/ansible/ssh/latte
