---
- name: Reboot nodes
  hosts: renaissance
  become: true

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: Reboot the worker node
      reboot:
        msg: "Reboot initiated by Ansible for maintenance"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
