---
- name: Update-packages
  hosts: renaissance
  become: yes

  vars_files:
    - secret_vars_common.yml

  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        force: yes

    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 3600
